export const SURVEY_LOAD = 'SURVEY_LOAD';
export const SURVEY_LOAD_SUCCESS = 'SURVEY_LOAD_SUCCESS';
export const SURVEY_LOAD_FAILED = 'SURVEY_LOAD_FAILED';
export const SURVEY_CHANGE_STEP = 'SURVEY_CHANGE_STEP';
